### ISSUE TITLE
运行报错 chrome版本80.0 是需要指定chromedivre路径和名字吗？

### ISSUE THREAD

**Issue by chinkaysin** [Jesseslco/taobao_auto_buy#5]
Traceback (most recent call last):
  File "manage.py", line 36, in <module>
    main()
  File "manage.py", line 32, in main
    taobao = Taobao(**config)
  File "/Users/chinkaysin/taobao_auto_buy/bin/tb.py", line 6, in __init__
    super().__init__(target_url, buy_time)
  File "/Users/chinkaysin/taobao_auto_buy/lib/base.py", line 28, in __init__
    self._browser = self._config_browser()
  File "/Users/chinkaysin/taobao_auto_buy/lib/base.py", line 90, in _config_browser
    driver_dir = self._get_driver_dir()
  File "/Users/chinkaysin/taobao_auto_buy/lib/base.py", line 80, in _get_driver_dir
    return os.path.join((driver_dir, "chromedriver_mac"))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not tuple

**Comment by Jesseslco** [comment]
是的 需要把chromedrier重新命名

     > Windows
     
       chromedriver_win.exe    
     > Linux
     
       chromedriver_linux
     > Mac
     
       chromedriver_mac

命名后放入 drivers/ 下

**Comment by Jesseslco** [comment]
> Traceback (most recent call last):
> File "manage.py", line 36, in
> main()
> File "manage.py", line 32, in main
> taobao = Taobao(**config)
> File "/Users/chinkaysin/taobao_auto_buy/bin/tb.py", line 6, in **init**
> super().**init**(target_url, buy_time)
> File "/Users/chinkaysin/taobao_auto_buy/lib/base.py", line 28, in **init**
> self._browser = self._config_browser()
> File "/Users/chinkaysin/taobao_auto_buy/lib/base.py", line 90, in _config_browser
> driver_dir = self._get_driver_dir()
> File "/Users/chinkaysin/taobao_auto_buy/lib/base.py", line 80, in _get_driver_dir
> return os.path.join((driver_dir, "chromedriver_mac"))
> File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/posixpath.py", line 80, in join
> a = os.fspath(a)
> TypeError: expected str, bytes or os.PathLike object, not tuple

是的 需要把chromedrier重新命名

 > Windows
 
   chromedriver_win.exe    
 > Linux
 
   chromedriver_linux
 > Mac
 
   chromedriver_mac
命名后放入 drivers/ 下

**Comment by niu541412** [comment]
同样报错。
taobao_auto_buy/lib/base.py line80 多了一对括号

**Comment by Jesseslco** [comment]
感谢反馈, 我修改下
